feat: install/uninstall modules from welcome window
MirageNet/Mirage pull request #593
Opened 2021-02-16 10:06 UTC by erikas-taroza

This PR will add functionality to the welcome window where users can install Mirage modules.

2021-02-17 21:34 UTC, uweenukr commented
can you resolve the TODO code smell by updating the names? then it should be good to go

2021-02-17 23:11 UTC, erikas-taroza commented
@uweenukr I will fix it when the modules have the namespace changed. Otherwise import will throw errors.

2021-02-19 06:30 UTC, erikas-taroza commented
Some modules still need their package names updated. I could change them right now but things can break.

2021-02-19 08:07 UTC, paulpach commented
Can you add a screenshot in the description?

2021-02-19 15:42 UTC, paulpach commented
maybe, for now,  we should only display the modules that actually work.  Discovery is not ready,  Momentum is not ready,  websockets are not ready.   We can just add them once they are good to go.

Also, please make the scrollbar cover the entire right-hand side, and only show it when needed.

2021-02-19 15:44 UTC, paulpach commented
Instead of "Modules",  let's change it to "Packages" to stay consistent with how unity calls them.

2021-02-20 18:10 UTC, paulpach requested changes
There are changes here that are unrelated to package installation.   Please move those changes to separate PRs.

2021-02-20 18:10 UTC, paulpach commented on Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
> +    <ui:VisualElement name="Banner" style="background-color: rgb(11, 12, 11);">
split this into another PR,  this has nothing to do with installing packages

2021-02-20 18:10 UTC, paulpach commented on Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
> +            <ui:VisualElement name="Welcome" style="flex-grow: 0; width: 100%; height: 100%; display: none;">
was this commited by accident?

2021-02-20 18:10 UTC, paulpach commented on Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
> +        private const string DiscordInviteUrl = "https://discord.gg/DTBPBYvexy";
separate PR,  unrelated to package installation

2021-02-20 18:10 UTC, paulpach commented on Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
> +        private static string screenToOpenKey = "MirageScreenToOpen";
split into separate PR.  Unrelated to package install

2021-02-20 18:10 UTC, paulpach commented on Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
> +        private static string firstTimeVersionKey = string.Empty;
split into separate PR

2021-02-21 00:41 UTC, merged